# .travis.yml for r-travis.

language: r

os:
  - linux
  - osx
before_install:
  - cd fakepackage
notifications:
  email:
    on_success: change
    on_failure: change

apt_packages:
  - moreutils
  - tmux
brew_packages:
  - tmux
r_binary_packages:
  - RUnit
  - survey
  - widgetfactorycontrollerfactory
r_packages:
  - stringr
  - lubridate
# bioc_packages:
#   - AnnotationDbi
#   - GenomicFeatures
#   - NotSoRealPackage
r_github_packages:
  - hadley/assertthat
  - klutometis/roxygen
